#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 16 12:24:55 2023

@author: daniyal
"""

import cv2
import numpy as np

# Read image and calculate histogram
image = cv2.imread('/home/daniyal/image-processing/img/balloons_lowcontrast_lowbrightness.png', cv2.IMREAD_GRAYSCALE)
histogram = cv2.calcHist([image], [0], None, [256], [0, 256])



# Function to calculate histogram flatness measure
def histogram_flatness_measure(histogram):
    N = len(histogram)
    H = np.mean(histogram)
    numerator = np.sum((histogram - H)**4) / N
    denominator = (np.sum((histogram - H)**2) / N)**2
    HFM = numerator / denominator
    return HFM

# Function to calculate histogram spread
def histogram_spread(histogram):
    cdf = np.cumsum(histogram)
    ncdf = cdf / np.sum(histogram)
    bin_75 = np.argwhere(ncdf >= 0.75)[0][0]
    bin_25 = np.argwhere(ncdf >= 0.25)[0][0]

    HS = (bin_75 - bin_25)/255
    return HS


# Calculate histogram flatness measure and histogram spread
HFM = histogram_flatness_measure(histogram)
HS = histogram_spread(histogram)

print('Histogram Flatness Measure:', HFM)
print('Histogram Spread:', HS)
